version: 2
jobs:
  build:
    
    working_directory: ~/simple-rest-server

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: simple-rest-server-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - run: export ARTIFACT_VERSION=`printf 'VERSION=${project.version}\n0\n' | mvn org.apache.maven.plugins:maven-help-plugin:2.2:evaluate | grep '^VERSION' | cut -d'=' -f2`
      
      - run: echo $ARTIFACT_VERSION
      
      - save_cache:
          paths:
            - ~/.m2
          key: simple-rest-server-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/simple-rest-server-{{ .Environment.ARTIFACT_VERSION }}.jar
